services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CleanupBundle\Command\AssetCleanCleanupCommand:
    public: true
    tags:
      - { name: 'console.command' }

