services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # COMMANDS
    #

    # auto-register all commands as services
    CleanupBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']
