services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # COMMANDS
    #

    # auto-register all commands as services
    CleanupBundle\Command:
        resource: '../src/Command'
        tags: ['console.command']
